import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typewriter from 'typewriter-effect'

export default function Home() {
  return (
    <>
      <Head>
        <title>WizCV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>WizCV.</p>
        </div>
        <div className={styles.oneliner}>
          <div className={styles.center}>
            <h1>
              Tinder for jobs.
            <Typewriter
            options={{
              strings: ['Upload your LinkedIn profile.    '],
              autoStart: true,
              loop: true,
              wrapperClassName: `${styles.gradienttext}`,
              cursorClassName: `${styles.gradienttext}`,
            }}
          />
            </h1>
          </div>
        </div>
        <h2 className={styles.subtext}>Unlock job opportunities by matching your profile with potential employers.</h2>
       <a target="_blank" rel='noreferrer' href="https://wizcv.xyz/devs/"><button className={styles.card}>Devs onClick = (getJob) </button></a>
       <a target="_blank" rel='noreferrer' href="https://wizcv.xyz/publish/"><button className={styles.card}>Publish job offers </button></a>
       <div className={styles.footer}>
          <p>Made by Ricardo Sandoval | Email: info@wizcv.xyz</p>
          <p>Copyright © 2023 WizCV</p>
        </div>
      </main>
    </>
  )
}